config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments

  get 'test' => 'welcome#test'

  get 'p/:id' => 'posts#show'
  get 'w/:id' => 'welcome#index'
  get 'u/:id' => 'welcome#index'
  get 'page/:id' => 'welcome#index'
  get 'new'   => 'welcome#index'
  get 'login' => 'welcome#index'
  get 'register' => 'welcome#index'
  get 'logout' => 'welcome#index'
  get 'forgot_password' => 'welcome#index'
  get 'me' => 'welcome#index'
  get 'ws' => 'welcome#index'
  get 'ws/new' => 'welcome#index'

  namespace :utilities, path: :util do
    get 'get_title'
    get 'get_thumb'
  end

  devise_for :users

  resources :users

  get 'worlds/index'
  get 'get_user' => 'application#get_user'

  root 'welcome#index'

  resources :posts do
    get 'vote', on: :member
  end
  resources :worlds

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_tree order: 'created_at DESC'

  belongs_to :commentable, polymorphic: true
  belongs_to :user
  before_create  :increment_counter
  before_destroy :decrement_counter

  scope :nested_all, ->() do
    hash_tree(limit_depth: 4)
  end

  def increment_counter
    klass = self.commentable_type.constantize
    klass.increment_counter(:comments_count, self.commentable_id)
  end

  def decrement_counter
    klass = self.commentable_type.constantize
    klass.decrement_counter(:comments_count, self.commentable_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    post_id   = params[:commentable_id]
    # For now let's only deal with Post
    post = Post.find(post_id);
    @comments = post.comments.nested_all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create

  if params[:comment][:parent_id].to_i > 0
    parent = Comment.find_by_id(params[:comment].delete(:parent_id))
    @comment = parent.children.build(comment_params)
  else
    @comment = Comment.new(comment_params)
  end

    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :flagged, :commentable_type, :commentable_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
  comments.map do |comment, nested_comments|
  render(comment) +
  (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: "replies") : nil)
end.join.html_safe
end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :flagged %><br>
    <%= f.check_box :flagged %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Flagged</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.flagged %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Flagged:</strong>
  <%= @comment.flagged %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>